# Generated by Django 3.2.12 on 2023-03-28 23:30

from django.db import migrations

def populate_status(apps, schemaeditor):
    status = {
        "published": "A blog post that is visibleto everyone.",
        "unpublished": "A blog post in draft mode, visible only to the author."
    }
    Status = apps.get_model("posts", "Status")
    for key, desc in status.items():
        status_obj = Status(name=key, description=desc)
        status_obj.save()



class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
